### PR TITLE
Add command line parser and version

### PR DESCRIPTION
**Pull request by muhammetasan**
#289

### CODE REVIEW

**Comment by oguzhaninan** [comment]
Thank you @muhammetasan :+1:

**Comment by zero77** [comment]
@muhammetasan 
Whats the command line argument because, everything i have tried just opened Stacer and does not output the version number.

**Comment by muhammetasanpix4d** [comment]
> @muhammetasan
> Whats the command line argument because, everything i have tried just opened Stacer and does not output the version number.

--version or -v should work. It is qt default

**Comment by zero77** [comment]
Thanks, but i have tried both and it just opened Stacer without displaying the version number.

**Comment by muhammetasan** [comment]
Are you building by yourself? Are you on correct branch ?

**Comment by zero77** [comment]
i am using the PPA Repository for ubuntu
Stacer v1.1.0

**Pull request merged**
